#Пользователи

## Создать пользователя
POST http://localhost:9000/users HTTP/1.1
Content-Type: application/json

{
  "email": "qwe@home.net",
  "name": "Andrew Black",
  "password": "qweqwe"
}

###

## Авторизация пользователя
POST http://localhost:9000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "qwe@home.net",
  "password": "qweqwe"
}

###

## Проверка состояния пользователя
GET http://localhost:9000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

DELETE http://localhost:9000/users/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json


# Фильмы

## Создать фильм
POST http://localhost:9000/films HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

{
  "title": "qwe@home.net",
  "description": "qweqwe",
  "year": 2001,
  "genre": "Comedy",
  "videoPreview": "http://video.org/preview/123144532",
  "videoPreview": "http://video.org/video/123144532",
  "starring": ["Актер Первый", "Актер Второй", "Актер Третий"],
  "director": "Братья знаменитые режиссеры",
  "runTime": 180,
  "posterImage": "http://images.org/poster/123144532",
  "backgroundImage": "http://posters.org/background/123144532",
  "backgroundColor": "red",
  "userId": {userID}
}

###

## Получить список фильмов
GET http://localhost:9000/films HTTP/1.1
Content-Type: application/json

###

## Получить детальную информацию о фильме
GET http://localhost:9000/films/{filmid} HTTP/1.1
Content-Type: application/json

###

## Удалить фильм
DELETE http://localhost:9000/films/{filmid} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

###

PUT http://localhost:9000/films/{filmid} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

{
  "title": "qwe@home.net",
  "description": "qweqwe",
  "year": 2001,
  "genre": "Comedy",
  "videoPreview": "http://video.org/preview/123144532",
  "videoPreview": "http://video.org/video/123144532",
  "starring": ["Актер Первый", "Актер Второй", "Актер Третий"],
  "director": "Братья знаменитые режиссеры",
  "runTime": 180,
  "posterImage": "http://images.org/poster/123144532",
  "backgroundImage": "http://posters.org/background/123144532",
  "backgroundColor": "red"
}

###

## Получить промо-фильм
DELETE http://localhost:9000/films/promo HTTP/1.1
Content-Type: application/json

###

## Получить список фильмов к просмотру
GET http://localhost:9000/films/favourites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

###

## Добавить фильм к просмотру
POST http://localhost:9000/films/{filmId}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

###

## Удалить фильм из списка к просмотру
POST http://localhost:9000/films/{filmId}/0 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

###

#Комментарии

## Добавить комментарий к фильму
POST http://localhost:9000/films/{filmId}/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InF3ZUBob21lLm5ldCIsImlkIjoiNjM1ZTYxNWZiMzA5MmJmZTZiMTBmZTYxIiwiaWF0IjoxNjY3MTI5NzQ5LCJleHAiOjE2NjczMDI1NDl9.Vf5Lj9KUTxiuYsVeivGDxqn4M_tA30AkHHHNuL-xm4c
Content-Type: application/json

{
  "text": "Хороший фильм, черт возьми!",
  "rating": 9
}

###

## Получить все комментарии к фильму
GET http://localhost:9000/films/{filmId}/comments HTTP/1.1
Content-Type: application/json
